config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name:'admin', password:'admin'

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страница o нас'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name:'admin', password:'admin', except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect

    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <p style="margin-bottom: 0; margin-top: 0; margin-right: 10px; color: #ffc107;">Posts</p>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><span>
            <%= link_to "Главная страница", home_path, :class => "nav-link px-2 text-secondary" %></span></li>
          <li><span>
            <%= link_to "Про нас", about_path, :class => "nav-link px-2 text-white" %></span></li>

        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <span><%= link_to "Добавление статьи", new_post_path, :class => "btn btn-outline-light me-2" %></span>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
  <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>

<% end %>

app/views/posts/index.html.erb
<h1>Все Ваши посты</h1>
<% @post.each do |post| %>
  <hr>
  <div class="alert alert-light">
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
    <%=  link_to "Читать далее", post_path(post), :class => 'btn btn-default' %>
  </div>
  <hr>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление поста</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
<p>
  Название <br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Текст статьи <br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить пост", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"}, :class => 'btn btn-danger' %>
<hr>

<h2>Все комментарии</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
  </div>
<% end %>

<hr>
<h2>Добавить комментарий</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Пользователь <br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст комментария <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit("Добавить комментарий ", {:class => 'btn btn-warning'}) %>
  </p>

<% end %>